print("Regndråber trommer mod ruden nu,")
print("kaffen er varm og koppen er blå.")
print("Verden suser afsted i et nu,")
print("men lige her kan vi trygt stå.")
print("Et lille smil i det fjerne lys,")
print("glemmer for altid vinterens gys.")
print("Dagen åbner sin stille favn,")
print("Hej Viktor :)")